# Generated by Django 5.0.7 on 2024-07-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя героя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение героя')),
                ('type', models.CharField(choices=[('STR', 'Сила'), ('AGI', 'Ловкость'), ('INT', 'Интеллект'), ('UNI', 'Универсальный')], default='STR', max_length=3, verbose_name='Атрибут')),
            ],
        ),
    ]
