# Generated by Django 5.0.7 on 2024-07-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
