# Generated by Django 5.0.7 on 2024-07-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0003_skinsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_dotabuff',
            field=models.URLField(blank=True, null=True),
        ),
    ]
