# Generated by Django 5.0.7 on 2024-07-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0004_menuitem_link_dotabuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='images', verbose_name='Иконка героя'),
        ),
    ]
