# Generated by Django 5.0.7 on 2024-07-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0005_menuitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsitem',
            name='hero_icon',
            field=models.ImageField(default='default/path/to/hero_icon.png', upload_to='hero_icons/'),
        ),
        migrations.AddField(
            model_name='skinsitem',
            name='hero_name',
            field=models.CharField(default='default/path/to/hero_icon.png', max_length=100),
            preserve_default=False,
        ),
    ]
