# Generated by Django 5.0.7 on 2024-07-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0006_skinsitem_hero_icon_skinsitem_hero_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinsitem',
            name='hero_icon',
        ),
        migrations.RemoveField(
            model_name='skinsitem',
            name='hero_name',
        ),
    ]
