# Generated by Django 5.0.7 on 2024-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0007_remove_skinsitem_hero_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название погоды')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение погоды')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на стим')),
                ('link_1', models.URLField(blank=True, null=True, verbose_name='Ссылка на лис-скинс')),
            ],
        ),
    ]
