# Generated by Django 5.0.7 on 2024-07-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0008_weatheritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinsitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
