# Generated by Django 5.0.7 on 2024-07-20 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsitem',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dotasiteview.menuitem'),
        ),
    ]
