# Generated by Django 5.0.7 on 2024-07-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0011_skinsitem_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinsitem',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название скина'),
        ),
    ]
