# Generated by Django 5.0.7 on 2024-07-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0012_alter_skinsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinsitem',
            name='hero_icon',
            field=models.ImageField(default=0, upload_to='images', verbose_name='Иконка героя для панели сортировки'),
            preserve_default=False,
        ),
    ]
