# Generated by Django 5.0.7 on 2024-07-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotasiteview', '0013_skinsitem_hero_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinsitem',
            old_name='hero_icon',
            new_name='icon',
        ),
    ]
